services:
  service:
    image: account-service:latest
    container_name: account-service
    depends_on:
      - db
#      - redis
    ports:
      - "8081:8081"
      - "7000:7000"
    environment:
      DB_SCHEMA: public
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: compose-postgres
      DB_USER: compose-postgres
      DB_PASSWORD: compose-postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      REDIS_PASS: sOmE_sEcUrE_pAsS

  db:
    image: postgres:latest
    container_name: account-service-db
    ports:
      - "8085:5432"
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres

#  redis:
#    image: redis:latest
#    container_name: account-service-redis
#    ports:
#      - "6379:6379"
#    command: redis-server --requirepass sOmE_sEcUrE_pAsS