server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?currentSchema=${DB_SCHEMA}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate

#flyway:
#  url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
#  schemas: ${DB_SCHEMA}
#  user: ${DB_USER}
#  password: ${DB_PASSWORD}

logging:
  level:
    org.springframework: INFO
    io.lettuce: TRACE
    com.test: INFO